from typing import Any, Protocol
from shared_contracts.jobs import JobStatus


class JobRepositoryPort(Protocol):
    def save_status(self, status: JobStatus) -> None: ...
    def load_status(self, job_id: str) -> JobStatus: ...
    def save_result(self, job_id: str, result: Any) -> None: ...
    def load_result(self, job_id: str) -> Any: ...
