from pathlib import Path
from typing import Any, Dict, Protocol, Tuple


class ModelRegistryPort(Protocol):
    def save(self, model_id: str, model: Any, preprocessing: Any, manifest: Dict) -> Path: ...
    def load(self, model_id: str) -> Tuple[Any, Any, Dict]: ...
    def list_models(self): ...
