"""Qt URL adapter around the original shared teaching asset catalog."""
from PySide6.QtCore import QUrl
from shared_presentation.teaching_assets import (
    ASSET_DIR,
    BODY_ASSET_KEYS,
    POST_STEM_KEY,
    FIBER_STAGE_KEY,
    ASSET_SUFFIXES,
    MESH_AXES,
    NATIVE_AABB_TOL_MM,
    ORIGIN_OUTPUT_FACE,
    ORIGIN_INPUT_FACE,
    ORIGIN_CENTER,
    ORIGIN_TOP,
    ORIGIN_BOTTOM,
    ORIGIN_HARDWARE,
    POST_BASE_KEY,
    MOUNT_RING_KEY,
    MOUNT_CLAMP_KEY,
    MOUNT_KM_KEY,
    MOUNT_PLATE_KEY,
    PLACEHOLDER_CYLINDER,
    PLACEHOLDER_CUBE,
    HALF_INCH_MM,
    POST_DIAMETER_MM,
    POST_DISPLAY_DIA_MM,
    LMR_WALL_MM,
    LMR_THICKNESS_MM,
    PH_PLATE_MM,
    DEFAULT_LENS_THICKNESS_MM,
    MIRROR_THICKNESS_MM,
    LASER_HOUSING_LENGTH_MM,
    LASER_HOUSING_DIA_MM,
    FIBER_HOUSING_LENGTH_MM,
    FIBER_HOUSING_DIA_MM,
    CCD_HOUSING_LENGTH_MM,
    CCD_HOUSING_FACE_MM,
    APERTURE_THICKNESS_MM,
    DEFAULT_APERTURE_DIA_MM,
    ISOLATOR_HOUSING_LENGTH_MM,
    ISOLATOR_HOUSING_DIA_MM,
    BREADBOARD_KEY,
    BREADBOARD_LENGTH_MM,
    BREADBOARD_WIDTH_MM,
    BREADBOARD_THICKNESS_MM,
    BREADBOARD_HOLE_PITCH_MM,
    BREADBOARD_HOLE_SIZE,
    STEM_BOARD_GAP_MM,
    FIBER_STAGE_DISPLAY_LENGTH_MM,
    FIBER_STAGE_DISPLAY_WIDTH_MM,
    FIBER_STAGE_DISPLAY_HEIGHT_MM,
    FIBER_MOUNT_PAD_LENGTH_MM,
    FIBER_MOUNT_PAD_WIDTH_MM,
    FIBER_MOUNT_PAD_HEIGHT_MM,
    FIBER_DISPLAY_LENGTH_MM,
    FIBER_DISPLAY_DIA_MM,
    HousingSpec,
    NativeMeshSpec,
    HousingTarget,
    MeshExtents,
    MeshPlacement,
    HOUSING_SPECS,
    target_aabb_for_housing,
    TARGET_MESH_SPECS,
    MOUNT_MESH_SPECS,
    MOUNT_KEY_BY_STYLE,
    NATIVE_MESH_SPECS,
    housing_spec,
    mesh_key_for_kind,
    visual_housing,
    fiber_stage_display_housing,
    stem_clearance_mm,
    stem_draw_height_mm,
    _axis_scale,
    fit_mesh_to_housing,
    stem_mesh_placement,
    resolve_asset_file,
    _glb_json,
    _position_accessor_indices,
    _mesh_extents_cached,
    mesh_extents,
    expected_asset_keys,
    _origin_violations,
    shipped_mesh_violations,
    inventory,
    check_assets,
    main,
)

def mesh_url(asset_key: str) -> str:
    path = resolve_asset_file(asset_key)
    if path is None:
        return ""
    return QUrl.fromLocalFile(str(path.resolve())).toString(QUrl.ComponentFormattingOption.FullyEncoded)

__all__ = ['ASSET_DIR', 'BODY_ASSET_KEYS', 'POST_STEM_KEY', 'FIBER_STAGE_KEY', 'ASSET_SUFFIXES', 'MESH_AXES', 'NATIVE_AABB_TOL_MM', 'ORIGIN_OUTPUT_FACE', 'ORIGIN_INPUT_FACE', 'ORIGIN_CENTER', 'ORIGIN_TOP', 'ORIGIN_BOTTOM', 'ORIGIN_HARDWARE', 'POST_BASE_KEY', 'MOUNT_RING_KEY', 'MOUNT_CLAMP_KEY', 'MOUNT_KM_KEY', 'MOUNT_PLATE_KEY', 'PLACEHOLDER_CYLINDER', 'PLACEHOLDER_CUBE', 'HALF_INCH_MM', 'POST_DIAMETER_MM', 'POST_DISPLAY_DIA_MM', 'LMR_WALL_MM', 'LMR_THICKNESS_MM', 'PH_PLATE_MM', 'DEFAULT_LENS_THICKNESS_MM', 'MIRROR_THICKNESS_MM', 'LASER_HOUSING_LENGTH_MM', 'LASER_HOUSING_DIA_MM', 'FIBER_HOUSING_LENGTH_MM', 'FIBER_HOUSING_DIA_MM', 'CCD_HOUSING_LENGTH_MM', 'CCD_HOUSING_FACE_MM', 'APERTURE_THICKNESS_MM', 'DEFAULT_APERTURE_DIA_MM', 'ISOLATOR_HOUSING_LENGTH_MM', 'ISOLATOR_HOUSING_DIA_MM', 'BREADBOARD_KEY', 'BREADBOARD_LENGTH_MM', 'BREADBOARD_WIDTH_MM', 'BREADBOARD_THICKNESS_MM', 'BREADBOARD_HOLE_PITCH_MM', 'BREADBOARD_HOLE_SIZE', 'STEM_BOARD_GAP_MM', 'FIBER_STAGE_DISPLAY_LENGTH_MM', 'FIBER_STAGE_DISPLAY_WIDTH_MM', 'FIBER_STAGE_DISPLAY_HEIGHT_MM', 'FIBER_MOUNT_PAD_LENGTH_MM', 'FIBER_MOUNT_PAD_WIDTH_MM', 'FIBER_MOUNT_PAD_HEIGHT_MM', 'FIBER_DISPLAY_LENGTH_MM', 'FIBER_DISPLAY_DIA_MM', 'HousingSpec', 'NativeMeshSpec', 'HousingTarget', 'MeshExtents', 'MeshPlacement', 'HOUSING_SPECS', 'target_aabb_for_housing', 'TARGET_MESH_SPECS', 'MOUNT_MESH_SPECS', 'MOUNT_KEY_BY_STYLE', 'NATIVE_MESH_SPECS', 'housing_spec', 'mesh_key_for_kind', 'visual_housing', 'fiber_stage_display_housing', 'stem_clearance_mm', 'stem_draw_height_mm', '_axis_scale', 'fit_mesh_to_housing', 'stem_mesh_placement', 'resolve_asset_file', '_glb_json', '_position_accessor_indices', '_mesh_extents_cached', 'mesh_extents', 'expected_asset_keys', '_origin_violations', 'shipped_mesh_violations', 'inventory', 'check_assets', 'main', 'mesh_url']

if __name__ == "__main__":
    raise SystemExit(main())
