

DATASET_EMPTY_SAMPLES = "DATASET_EMPTY_SAMPLES"
DATASET_SURFACE_COUNT_EXCEEDED = "DATASET_SURFACE_COUNT_EXCEEDED"
DATASET_LAST_SURFACE_DISTANCE_INVALID = "DATASET_LAST_SURFACE_DISTANCE_INVALID"
DATASET_UNSUPPORTED_MATERIAL = "DATASET_UNSUPPORTED_MATERIAL"

DATASET_HEADLESS_SIMULATION_FAILED = "DATASET_HEADLESS_SIMULATION_FAILED"
DATASET_COUPLING_EFFICIENCY_MISSING = "DATASET_COUPLING_EFFICIENCY_MISSING"
DATASET_NON_PHYSICAL_RESULT = "DATASET_NON_PHYSICAL_RESULT"

DATASET_NOT_FOUND = "DATASET_NOT_FOUND"
DATASET_FILE_NOT_FOUND = "DATASET_FILE_NOT_FOUND"
DATASET_TARGET_COLUMN_MISMATCH = "DATASET_TARGET_COLUMN_MISMATCH"
